<?php
/**
 * @file
 * deal with highlight function in message library
 *
 * This module provides the following features
 *
 * - Hightlight the search text being searching in the result
 * - Allow navigation among the highlighted message
 *
 * - Also, this module provides some highlight irrelevant feature:
 *   - Navigation among the threats in the search result
 *   - Go back to the current search
 */

/**
 * Implements hook_init()
 */
function message_library_highlight_init() {
  drupal_add_css(drupal_get_path('module', 'message_library_highlight') . '/css/highlight.css');
}

/**
 * Implements hook_theme()
 */
function message_library_highlight_theme() {
  return array(
    'message_library_prev_message_link' => array(
       'variables' => array('dest_tid' => NULL, 'dest_nid' => NULL),
     ),
    'message_library_next_message_link' => array(
      'variables' => array('dest_tid' => NULL, 'dest_nid' => NULL),
     ),
    'message_library_threat_nav_links' => array(
      'variables' => array('next_tid' => NULL, 'prev_tid' => NULL, 'crt_search_link' => NULL),
     ),
  );
}

/*
 * Theme function for a prev highlighted message link
 */
function theme_message_library_prev_message_link($vars) {
  $output = '';
  // Both the threat's tid and a a specific message's nid are required
  if (!empty($vars['dest_tid']) && !empty($vars['dest_nid'])) {
    $output .= l(t('Previous highlight message'), 'message-library/threat/' . $vars['dest_tid'], array(
        'fragment' => $vars['dest_nid'], 'attributes' => array('class' => array('highlight_link prev'))));
  }
  return $output;
}

/*
 * Theme function for a next highlighted message link
 */
function theme_message_library_next_message_link($vars) {
  $output = '';
  // Both the threat's tid and a a specific message's nid are required
  if (!empty($vars['dest_tid']) && !empty($vars['dest_nid'])) {
    $output .= l(t('Next highlight message'), 'message-library/threat/' . $vars['dest_tid'], array(
        'fragment' => $vars['dest_nid'], 'attributes' => array('class' => array('highlight_link next'))));
  }
  return $output;
}

/**
 * Theme function for the threat navigation.
 * It will return 3 links:
 * - One to the message library search page with the current arguments
 * - One for the previous threat page in the search result
 * - One for the next threat page in the search result
 */
function theme_message_library_threat_nav_links($vars) {
  $output = '';
  $links = array();
  extract($vars);
  if (!empty($_SESSION['message_library_result'])) {
    $links[] = array(
      'title' => t('Back to current selection'),
      'href' => 'message-library',
      'attributes' => array('class' => array('crt-selection')),
    );
  }

  if (!empty($prev_tid)) {
    $links[] = array(
      'title' => t('Previous threat'),
      'href' => 'message-library/threat/' . $prev_tid,
      'attributes' => array('class' => array('prev-threat')),
    );
  }
  if (!empty($next_tid)) {
    $links[] = array(
      'title' => t('Next threat'),
      'href' => 'message-library/threat/' . $next_tid,
      'attributes' => array('class' => array('next-threat')),
    );
  }

  if (!empty($links)) {
    $output .= theme('links', array('links' => $links));
  }
  return $output;
}

/**
 * Implements hook_views_pre_render()
 */
function message_library_highlight_views_pre_render(&$view) {
  if ($view->name == 'messsage_library_threat' && $view->current_display == 'attachment_header') {
    $prev_tid = $next_tid = '';
    if (!empty($view->args) && !empty($view->args[0])) {
      $tid = reset($view->args);

      // Get the previous threat's tid
      $prev_tid = _message_library_hightlight_get_adjacent_threat_tid($tid, 'prev');

      // Get the next threat's tid
      $next_tid = _message_library_hightlight_get_adjacent_threat_tid($tid, 'next');
    }
    $view->attachment_before .= theme('message_library_threat_nav_links', compact('prev_tid', 'next_tid'));
  }
}

/**
 * Implements hook_views_api()
 */
function message_library_highlight_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_views_pre_execute()
 */
function message_library_highlight_views_pre_execute(&$view) {
  // For the message_library view
  if ($view->name === 'message_library') {
    $search_text = !empty($view->exposed_input['ml_search_text']) ?
      trim($view->exposed_input['ml_search_text']) : '';

    $query = clone $view->query->getSearchApiQuery();
    $res = $query->range()->execute(); // same order when you are viewing detail page

    // Group all the messages in the search result by the threat
    $messages = array();
    if (!empty($res['results'])) {
      $entities = entity_load($query->getIndex()->item_type, array_keys($res['results']));

      foreach($entities as $entity) {
        // Get the tid of the threat to which the current message belongs
        $items = field_get_items('node', $entity, 'field_message_threat');

        foreach ($items as $item) {
          // Check whether the threat term is valid and get some detail info
          $threat_term = taxonomy_term_load($item['tid']);
          if (empty($threat_term)) continue;

          if (!isset($messages[$item['tid']]['name'])) {
            $messages[$item['tid']]['name'] = $threat_term->name;
          }

          if (!isset($messages[$item['tid']]['messages'])) {
            $messages[$item['tid']]['messages'] = array();
          }

          $messages[$item['tid']]['messages'][$entity->nid] = $entity->title;
        }
      }
    }

    if (!empty($messages)) {
      $_SESSION['message_library_result'] = $messages;

      if (!empty($search_text)) {
        $_SESSION['hl_messages'] = $messages;
        $_SESSION['hl_words'] = preg_split('|\s+|', $search_text);
      }
    }

    if (empty($search_text) || empty($messages)) {
      unset($_SESSION['hl_messages']);
      unset($_SESSION['hl_words']);
    }

    global $base_root;
    $_SESSION['message_library_active_selection'] = $base_root . request_uri();
  }
}

/**
 * Implements hook_preprocess_node()
 */
function message_library_highlight_preprocess_node(&$vars) {
  // Only preprocess 'message' nodes
  if ($vars['type'] != 'message') return;

  // @todo: Only hightlight when it's actually from the search
  $page_view = views_get_page_view();
  $nid = $vars['nid'];

  if ($page_view->name == 'messsage_library_threat') {
    // Get the threat term's tid being displayed
    if (!empty($page_view->args) && !empty($page_view->args[0])) {
      $threat_tid = $page_view->args[0];

      // Check if there is any message should be hightlighted
      if (!empty($_SESSION['hl_messages']) && !empty($_SESSION['hl_messages'][$threat_tid])) {
        // Make sure this message is meant to be hightlighted
        if (!empty($_SESSION['hl_messages'][$threat_tid]['messages']) &&
            !empty($_SESSION['hl_messages'][$threat_tid]['messages'][$nid])) {
          // Add necessary class so hightlight style can be applied
          $vars['classes_array'][] = 'highlight';

          // Prepare the prev link
          $prev_dest = _message_library_hightlight_get_prev_message($threat_tid, $nid);
          $vars['prev_highlighted_message'] = theme('message_library_prev_message_link', $prev_dest);

          // Prepare the next link
          $next_dest = _message_library_hightlight_get_next_message($threat_tid, $nid);
          $vars['next_highlighted_message'] = theme('message_library_next_message_link', $next_dest);
        }
      }
      else {
        // @todo:
        // No message should be hightlight at all
      }
    }
  }
}

/**
 * Implements hook_preprocess_views_view_table()
 */
function message_library_highlight_preprocess_views_view_table(& $vars) {
  if ($vars['view']->name === 'message_library') {
    foreach($vars['rows'] as & $row) {
      $row['field_message_threat_field_threat_category'] = _search_highlight_content($row['field_message_threat_field_threat_category']);
      $row['field_message_threat'] = _search_highlight_content($row['field_message_threat']);
      $row['title_1'] = _search_highlight_content($row['title_1']);
      $row['field_message_group_mess'] = _search_highlight_content($row['field_message_group_mess']);
      $row['field_message_example_communic'] = _search_highlight_content($row['field_message_example_communic']);
    }
  }
}

/**
 * Implements hook_preprocess_views_view_unformatted()
 */
function message_library_highlight_preprocess_views_view_unformatted(& $vars) {
  if ($vars['view']->name === 'messsage_library_threat') {
    foreach($vars['rows'] as & $row) {
      $row = _search_highlight_content($row);
    }
  }
}

// copy from previous version
function _search_highlight_content($content) {
  if (isset($_SESSION['hl_words']) && !empty($_SESSION['hl_words'])) {
    $highlights = $_SESSION['hl_words'];
    foreach ($highlights as $highlight) {
      if ($highlight != '') {
        // on echappe les caractères regexp
        $highlight = str_replace(array('\\', '/', '?', '.', '*', '+', '-', '(', ')', '[', ']', '^', '$', '{', '}', '|'), array('\\\\', '\/', '\?', '\.', '\*', '\+', '\-', '\(', '\)', '\[', '\]', '\^', '\$', '\{', '\}', '\|'), $highlight);
        //$pattern = '/\b('.$highlight.')\b(?=[^><]*<|.$)/i'; // recherche texte strict + "/(\w*?(?:$keywordsPattern)\w*)/ui" si highlight mot complet
        $pattern = '/\b(' . _search_highlight_format_term($highlight) . ')\b(?=[^><]*<|.$)/i'; // recherche texte non strict
        $replacement = '<span class="search_highlight">\1</span>';
        // on passe par un <div> car j'arrive pas à faire l'expression régulière correctement
        $content_div = preg_replace($pattern, $replacement, '<div>' . $content . '</div>');
        $content = substr($content_div, 5, -6);
      }
    }
  }
  return $content;
}

function _search_highlight_format_term($term) {
  return str_replace(array('(', ')'), array('\(', '\)'), $term);
}

/**
 * Find the next message that should be highlighted
 */
function _message_library_hightlight_get_prev_message($threat_tid, $message_nid) {
  $dest_tid = $dest_nid = '';

  if (!empty($threat_tid)) {
    // First try to find the previous message in the current threat group
    $sorted_nids = _message_library_hightlight_sort_highlighted_message_by_threat_view($threat_tid);
    // Get the previous highlighed message in the current threat
    reset($sorted_nids);
    while (current($sorted_nids) != NULL && current($sorted_nids) != $message_nid) {
      next($sorted_nids);
    }
    $next_message_nid = prev($sorted_nids);

    // Found a previous message in the same threat group
    if (!empty($next_message_nid)) {
      // drupal_set_message(t('Found previous message for message !tid#!nid : !_tid#!_nid.', array(
      //    '!tid' => $threat_tid, '!nid' => $message_nid, '!_tid' => $threat_tid, '!_nid' => $next_message_nid)));

      $dest_tid = $threat_tid;
      $dest_nid = $next_message_nid;
    }
    // Can't found previous message in the current threat group, try to find it
    // in the previous threat group
    else {
      // drupal_set_message(t('Can\'t find previous message for message !tid#!nid on the current threat page.', array(
      //    '!tid' => $threat_tid, '!nid' => $message_nid)));
      // Get the prev threat
      $prev_threat_tid = _message_library_hightlight_get_adjacent_highlight_threat_tid($threat_tid, 'prev');

      // @todo: This should keep searching backword
      // There is a threat group ahead available
      if (!empty($prev_threat_tid)) {
        // The message should be the last message in the previous threat group
        // that is available
        $sorted_nids = _message_library_hightlight_sort_highlighted_message_by_threat_view($prev_threat_tid);

        if (!empty($sorted_nids)) {
          $next_message_nid = end($sorted_nids);

          $dest_tid = $prev_threat_tid;
          $dest_nid = $next_message_nid;

          // @todo: If not found, keep looking backward
          // drupal_set_message(t('Found previous message for message !tid#!nid : !_tid#!_nid.', array(
          //    '!tid' => $threat_tid, '!nid' => $message_nid, '!_tid' => $prev_threat_tid, '!_nid' => $next_message_nid)));
        }
      }
      // No threat group ahead, then this message is the first one in the whole
      else {
        // Not available
        // drupal_set_message(t('There is no threat group before threat !tid.', array('!tid' => $threat_tid)));
      }
    }
  }
  else {
    // The $threat_tid is required,
  }

  return compact('dest_tid', 'dest_nid');
}

/**
 * Find the next message that should be highlighted
 */
function _message_library_hightlight_get_next_message($threat_tid, $message_nid) {
  $dest_tid = $dest_nid = '';

  if (!empty($threat_tid)) {
    // First try to find the next message in the current threat group
    $sorted_nids = _message_library_hightlight_sort_highlighted_message_by_threat_view($threat_tid);
    // Get the previous highlighed message in the current threat
    reset($sorted_nids);
    while (current($sorted_nids) != NULL && current($sorted_nids) != $message_nid) {
      next($sorted_nids);
    }
    $next_message_nid = next($sorted_nids);

    // Found a previous message in the same threat group
    if (!empty($next_message_nid)) {
      // drupal_set_message(t('Found next message for message !tid#!nid : !_tid#!_nid.', array(
      //    '!tid' => $threat_tid, '!nid' => $message_nid, '!_tid' => $threat_tid, '!_nid' => $next_message_nid)));

      $dest_tid = $threat_tid;
      $dest_nid = $next_message_nid;
    }
    // Can't found next message in the current threat group, try to find it
    // in the next threat group
    else {
      // drupal_set_message(t('Can\'t find next message for message !tid#!nid on the current threat page.', array(
      //    '!tid' => $threat_tid, '!nid' => $message_nid)));
      // Get the next threat
      $next_threat_tid = _message_library_hightlight_get_adjacent_highlight_threat_tid($threat_tid, 'next');

      // @todo: This should keep searching forward
      // There is a threat group ahead available
      if (!empty($next_threat_tid)) {
        // The message should be the last message in the previous threat group
        // that is available
        $sorted_nids = _message_library_hightlight_sort_highlighted_message_by_threat_view($next_threat_tid);

        if (!empty($sorted_nids)) {
          $next_message_nid = end($sorted_nids);

          $dest_tid = $next_threat_tid;
          $dest_nid = $next_message_nid;

          // @todo: If not found, keep looking backward
          // drupal_set_message(t('Found next message for message !tid#!nid : !_tid#!_nid.', array(
          //    '!tid' => $threat_tid, '!nid' => $message_nid, '!_tid' => $next_threat_tid, '!_nid' => $next_message_nid)));
        }
      }
      // No threat group ahead, then this message is the first one in the whole
      else {
        // Not available
        // drupal_set_message(t('There is no threat group after threat !tid.', array('!tid' => $threat_tid)));
      }
    }
  }
  else {
    // The $threat_tid is required,
  }

  return compact('dest_tid', 'dest_nid');
}

/**
 * Get the prev/next threat in the search result of the message library that
 * should be highlighted
 */
function _message_library_hightlight_get_adjacent_highlight_threat_tid($tid, $op) {
  if (!in_array($op, array('prev, next'))) {
    // drupal_set_message('Finding ' . $op . ' of ' . $tid);
    if (!empty($_SESSION['hl_messages']) && !empty($_SESSION['hl_messages'][$tid])) {
      reset($_SESSION['hl_messages']);
      while(key($_SESSION['hl_messages']) != null && key($_SESSION['hl_messages']) != $tid) {
        next($_SESSION['hl_messages']);
      }
      ($op == 'prev') ? prev($_SESSION['hl_messages']) : next($_SESSION['hl_messages']);
      return key($_SESSION['hl_messages']);
    }
  }
  return NULL;
}

/**
 * Get the prev/next threat in the search result of the message library
 */
function _message_library_hightlight_get_adjacent_threat_tid($tid, $op) {
  if (!in_array($op, array('prev, next'))) {
    if (!empty($_SESSION['message_library_result']) && !empty($_SESSION['message_library_result'][$tid])) {
      reset($_SESSION['message_library_result']);
      while(key($_SESSION['message_library_result']) != null && key($_SESSION['message_library_result']) != $tid) {
        next($_SESSION['message_library_result']);
      }
      ($op == 'prev') ? prev($_SESSION['message_library_result']) : next($_SESSION['message_library_result']);
      return key($_SESSION['message_library_result']);
    }
  }
  return NULL;
}

/**
 * Extract the message node nids from the view 'message_library_threat'
 */
function _message_library_highlight_extract_threat_view_items($items) {
  $nids = array();
  foreach ($items as $item) {
    if (!empty($item->nid)) {
      $nids[] = $item->nid;
    }
  }
  return $nids;
}

/**
 * Sort the hightlight messages according the order in message_library_threat
 *
 * @return Array of message nids whose order is in accordance with the oder
 *         appearing on the message_library_threat views
 */
function _message_library_hightlight_sort_highlighted_message_by_threat_view($tid) {
  // All messages in a threat
  $items = views_get_view_result('messsage_library_threat', 'main_page', $tid);
  $message_nids = _message_library_highlight_extract_threat_view_items($items);

  // All messages in a threat that should be hightlighted
  $highlighted_message_nids = array();
  if ( !empty($_SESSION['hl_messages'])
    && !empty($_SESSION['hl_messages'][$tid])
    && !empty($_SESSION['hl_messages'][$tid]['messages'])) {
    $highlighted_message_nids = array_keys($_SESSION['hl_messages'][$tid]['messages']);
  }

  //dpm(compact('message_nids', 'highlighted_message_nids'));
  $sorted = array();
  $sorted = array_intersect($message_nids, $highlighted_message_nids);
  return $sorted;
}
