<?php

/**
 * Implements hook_init().
 */
// function download_email_init() {
//   drupal_add_js(drupal_get_path('module', 'download_email') . '/js/download_email.js');
//   drupal_add_css(drupal_get_path('module', 'download_email') . '/css/download_email.css');
// }

/**
 * Implements hook_block_info().
 */
function download_email_block_info() {
  // TODO Rename block deltas (e.g. delta-0) to readable strings.
  if (TRUE) {
    $blocks['delta-0'] = array(
      'info' => t('Download/Email links'),
      'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
  }
}

/**
 * Implements hook_block_view().
 */
function download_email_block_view($delta) {
  // TODO Rename block deltas (e.g. delta-0) to readable strings.
  if (TRUE) {
    $block = array();
    switch ($delta) {
      case 'delta-0':
        $block = array(
          'subject' => t('Download/Email links'),
          'content' => theme('download_email'),
        );
        break;
    }
    return $block;
  }
}

/**
 * Implements hook_block().
 */
function download_email_block_OLD($op = 'list', $delta = 0, $edit = array()) { }

/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return unknown_type
 */
function download_email_theme($existing, $type, $theme, $path) {
  return array(
    'download_email' => array(
      'template' => 'templates/download_email',
      'variables' => array(),
    ),
  );
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function download_email_getRTFEmailUrl($arg0 = "", $arg1 = "") {
  $extUrl = export2rtf_get_url(arg(0), arg(1));
  return 'mailto:?body=' . t("Download the RTF from the server at the URL : ") . 'http://' . $_SERVER['HTTP_HOST'] . $extUrl;
}
