<?php

/**
 * @file
 * ...
 */

/**
 * Implements hook_views_api().
 */
function message_library_views_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'message_library_views') . '/views',
  );
}

/**
 * Helper functions.
 */

/**
 * Get all threat nodes from a search (view).
 */
function message_library_views_search_all_threat($cache_id, $query) {
  if ($current_search = search_api_current_search($cache_id)) {
    return $current_search[1];
  }

  $api_query = clone $query->getSearchApiQuery();
  $api_query->range(NULL, NULL);
  $result = $api_query->execute();
  if (!empty($result['results'])) {
    // Load all the entities.
    // @see EntityFieldHandlerHelper::pre_render().
    $entities = entity_load($query->getIndex()->item_type, array_keys($result['results']));

    $threat_terms = array();

    // Each message node
    foreach ($entities as $node) {
      // Extract the threat tids
      if (!empty($node->field_message_threat['und'])) {
        foreach($node->field_message_threat['und'] as $item) {
          if (!empty($item['tid'])) {
            $threat_term_obj = taxonomy_term_load($item['tid']);
            if (empty($threat_term_obj)) continue;
            $threat_terms[$threat_term_obj->tid] = $threat_term_obj->name;
          }
        }
      }
    }

    $threat_terms = array_unique($threat_terms);
    // Sort key threat's tid, numeric key ASC
    ksort($threat_terms, SORT_NUMERIC);

    // Cache.
    search_api_current_search($cache_id, $api_query, $threat_terms);
  }

  return $threat_terms;
}


