<?php

/**
 * Implements hook_permission().
 */
function message_library_tou_permission() {
  return array(
    'administer notices warning' => array(
      'title' => t('administer notices warning'),
    ),
  );
}

/**
 * Implements hook_menu()
 */
function message_library_tou_menu() {
  $items = array();

  $items['message-library-cgi'] = array(
    'title' => 'Message Library CGI',
    'description' => 'Display a TOU page for Message Library.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('message_library_tou_cgi_form'),
    'file' => 'includes/message_library_tou.pages.inc',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['message_library_tou/getmessage'] = array(
    'title' => 'IAA Notices Warning Message',
    'page callback' => 'message_library_tou_get_message',
    'file' => 'includes/message_library_tou.pages.inc',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['message_library_tou/formlogin'] = array(
    'title' => 'IAA Notices Warning Form Login',
    'page callback' => 'message_library_tou_form_login',
    'file' => 'includes/message_library_tou.pages.inc',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['message_library_tou/login'] = array(
    'title' => 'IAA Notices Warning Login',
    'page callback' => 'message_library_tou_login',
    'file' => 'includes/message_library_tou.pages.inc',
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_CALLBACK,
  );

  $items['cgi-message-library/formlogin'] = array(
    'title' => 'Message Library CGI',
    'page callback' => 'message_library_tou_cgi_form_login',
    'file' => 'includes/message_library_tou.pages.inc',
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_CALLBACK,
  );

  $items['cgi-message-library/login'] = array(
    'title' => 'Message Library CGI',
    'page callback' => 'message_library_tou_cgi_login',
    'file' => 'includes/message_library_tou.pages.inc',
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme()
 */
function message_library_tou_theme($existing, $type, $theme, $path) {
  return array(
    'message_library_tou_form_login' => array(
      'template' => 'templates/message_library_tou_form_login',
      'variables' => array(
        'nid' => '',
      ),
    ),
    'message_library_tou_cgi_form_login' => array(
      'template' => 'templates/message_library_tou_cgi_form_login',
      'variables' => array(
      ),
    ),
  );
}


/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function message_library_tou_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'message_library_tou_login_block') {
    $form['#action'] = $_SERVER['HTTP_REFERER'];
    $form["#submit"][] = "message_library_tou_user_form_submit";
  }
}


/**
 * Implements hook_url_inbound_alter()
 */
function message_library_tou_url_inbound_alter(&$path, $original_path, $path_language) {
  if (arg(0, $original_path) !== 'message-library') return;

  if (!message_library_tou_get_cgi_access()) {
    drupal_goto('message-library-cgi', array('query' => drupal_get_destination()));
  };
}


/**
 * Check if the user can directly access the Message Library by checking whether
 * he has agree it.
 *
 * @return bool
 *  TRUE if the user can have direct access, otherwise FALSE
 */
function message_library_tou_get_cgi_access() {
  if (user_is_logged_in()) {
    $query = 'SELECT id FROM {message_library_tou_cgi} WHERE accepted = :accepted AND uid = :uid;';
    $show = db_query($query,array(':accepted' => 1, ':uid' => $user->uid))
      ->fetchField();
  }
  else {
    $show = !empty($_SESSION['message_library_tou_cgi']);
  }
  return (bool)$show;
}


/**
 * Save the acceptance of TOU either in db or session
 */
function message_library_tou_save_cgi_access() {
  if (user_is_logged_in()) {
    db_insert('message_library_tou_cgi')
      ->fields(array('accepted' => 1,'uid' => $user->uid))
      ->execute();
  }
  else {
    $_SESSION['message_library_tou_cgi'] = TRUE;
  }
}


/**
 * Implements template_preprocess_THEMENAME()
 */
function template_preprocess_message_library_tou_cgi(&$vars) {
  // TOU body
  $vars['tou_text'] = isset($vars['node']->body['und'][0]['value']) ?
    $vars['node']->body['und'][0]['value'] : '';
  $destination = drupal_get_destination();
  $vars['destination'] = $destination['destination'];
  // Form's action url
  $vars['action_url'] = url("cgi-message-library/accepted");
}
