<?php

/**
 * Implements hook_permission().
 */
function message_library_tou_permission() {
  return array(
    'administer notices warning' => array(
      'title' => t('administer notices warning'),
    ),
  );
}

/**
 * Implements hook_menu()
 */
function message_library_tou_menu() {
  $items = array();

  $items['message-library-cgi'] = array(
    'title' => 'Message Library Terms of Use',
    'description' => 'Display a TOU page for Message Library.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('message_library_tou_cgi_form'),
    'file' => 'includes/message_library_tou.pages.inc',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme()
 */
function message_library_tou_theme($existing, $type, $theme, $path) {
  return array(
    'message_library_tou_form_login' => array(
      'template' => 'templates/message_library_tou_form_login',
      'variables' => array(
        'nid' => '',
      ),
    ),
    'message_library_tou_cgi_form_login' => array(
      'template' => 'templates/message_library_tou_cgi_form_login',
      'variables' => array(
      ),
    ),
  );
}


/**
 * Implements hook_url_inbound_alter()
 */
function message_library_tou_url_inbound_alter(&$path, $original_path, $path_language) {
  if (arg(0, $original_path) == 'message-library') {
    // Prevent the edit link on the content listing admin page
    // (eg. message-library/message/what-think-about/edit) from working
    if ((arg(1, $original_path) == 'message') && ($arg(3, $original_path) == 'edit')) {
      return;
    }

    if (!message_library_tou_get_cgi_access()) {
      $desination = drupal_get_destination();
      drupal_goto('message-library-cgi', array('query' => array(
       'cgi-destination' => $desination['destination'])));
    };
  }
}


/**
 * Check if the user can directly access the Message Library by checking whether
 * he has agreed the TOU before.
 *
 * @return bool
 *  TRUE if the user can have direct access, otherwise FALSE
 */
function message_library_tou_get_cgi_access() {
  if (isset($_SESSION) && !empty($_SESSION['message_library_tou_cgi'])) {
    return TRUE;
  }

  if (user_is_logged_in()) {
    global $user;
    $query = 'SELECT id FROM {message_library_tou_cgi} WHERE accepted = :accepted AND uid = :uid;';
    $show = db_query($query,array(':accepted' => 1, ':uid' => $user->uid))->fetchField();
    return (bool) $show;
  }

  return FALSE;
}


/**
 * Save the acceptance of TOU either in db or session
 */
function message_library_tou_save_cgi_access() {
  $_SESSION['message_library_tou_cgi'] = TRUE;

  if (user_is_logged_in()) {
    global $user;
    db_merge('message_library_tou_cgi')
      ->key(array('uid' => $user->uid))
      ->fields(array('accepted' => 1))
      ->execute();
  }
}

/**
 * Implements hook_user_login()
 */
function message_library_user_login(&$edit, $account) {
  if (!empty($edit['values']['message_library_tou_agreed'])) {
    message_library_tou_save_cgi_access();
  }
}
