<?php

$path = drupal_get_path('module', 'export2rtf');
include_once  $path . '/libraries/messageRtfFile.php';

/**
 * Implements hook_menu().
 */
function export2rtf_menu() {
  $items = array();
  $items['export2rtf/%'] = array(
    'page callback' => 'export2rtf_node',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'file' => 'includes/export2rtf.user.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Implements hook_block_info().
 */
function export2rtf_block_info() {
  if (TRUE) {
    $blocks['export_to_rtf_link'] = array(
      'info' => t('Export To RTF link'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
  }
}


/**
 * Implements hook_block_view().
 */
function export2rtf_block_view($delta) {
  if (TRUE) {
    $block = array();
    switch ($delta) {
      case 'export_to_rtf_link':
        $block = array(
          'subject' => t('Export To RTF links'),
          'content' => theme('export2rtf'),
        );
        break;
    }
    return $block;
  }
}


/**
 * Implements hook_theme().
 */
function export2rtf_theme($existing, $type, $theme, $path) {
  return array(
    'export2rtf' => array(
      'template' => 'templates/export2rtf',
      'variables' => array(),
    ),
  );
}


/**
 * Get the base url
 */
function export2rtf_get_url() {
  // For a single node
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    return url('export2rtf/') . arg(1);
  }

  //return url('export2rtf', array('absolute' => TRUE));
  return url('export2rtf');
}
