<?php

include_once 'libraries/messageRtfFile.php';

/**
 * Implements hook_init().
 */
function export2rtf_init() {
  drupal_add_js(drupal_get_path('module', 'export2rtf') . '/js/export2rtf.js');
  drupal_add_css(drupal_get_path('module', 'export2rtf') . '/css/export2rtf.css');
}

/**
 * Implementation of hook_menu().
 */
function export2rtf_menu() {
  $items = array();
  $items['export2rtf/%'] = array(
    'page callback' => 'export2rtf_node',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'file' => 'includes/export2rtf.user.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_block().
 */
function export2rtf_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Export To RTF link'),
      'cache' => BLOCK_CACHE_PER_ROLE
    );
    return $blocks;
  }
  else if ($op == 'view') {
    $block = array();
    switch ($delta) {
      case 0 :
        $block = array(
          'subject' => t('Export To RTF links'),
          'content' => theme('export2rtf')
        );
        break;
    }
    return $block;
  }
}


/**
 * Implements of hook_theme()
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return unknown_type
 */
function export2rtf_theme($existing, $type, $theme, $path) {
  return array(
    'export2rtf' => array(
      'template' => 'templates/export2rtf',
      'arguments' => array()
    )
  );
}


function export2rtf_getUrl($arg0 = "", $arg1 = "") {
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    return url("export2rtf/").arg(1);
  }
  return url("export2rtf");
}