<?php

/**
 * @file
 * A collection of the theming to the Message Library
 */

/**
 * Preprocess variables for page.tpl.php
 */
function message_library_theme_preprocess_page(&$variables) {
  if (empty($variables['title_suffix'])) {
    $variables['title_suffix'] = array();
  }

  $variables['title_suffix']['message_library_theme'] = array();
}


/**
 * Implements hook_views_api()
 */
function message_library_theme_views_api() {
  $path = drupal_get_path('module', 'message_library_theme');
  return array(
    'api' => 3,
    'path' => $path,
    'template path' => $path. '/templates',
  );
}


/**
 * Implements hook_form_alter()
 */
function message_library_theme_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'message_library_theme');

  if ($form['#id'] == 'views-exposed-form-message-library-search-page') {
    $form['#attached']['js'][]  = $path . '/message_library_theme.js';
    $form['#attached']['css'][] = $path . '/message_library_theme.css';
    // Note: use `dpm(drupal_get_library('system'));` to check what libraries
    // are available.
    $form['#attached']['library'][]  = array('system', 'drupal.collapse');
  }
}


/**
 * Implements MODULENAME_preprocess_hook()
 */
function message_library_theme_preprocess_views_exposed_form(&$vars) {
  $form = $vars['form'];
  if ($form['#id'] == 'views-exposed-form-message-library-search-page') {
    // If there are values set in the 'Advanced search', then don't set the
    // default collapsed status
    $vars['advanced_search_collapsed'] = TRUE;

    $advanced_widgets = array(
      'issue',
      'threat',
      'at_risk_group',
      'target_audience',
    );

    foreach ($advanced_widgets as $widget_name) {
      $value = $form[$widget_name]['#value'];
      $type = $form[$widget_name]['#type'];

      if (($type == 'select' && strtolower($value) !== 'all') ||
          ($type == 'text' && !empty($value))) {
        $vars['advanced_search_collapsed'] = FALSE;
        continue;
      }
    }
  }
}
