<?php

include_once 'message_library_help.features.inc';

/**
 * Implements hook_form_alter()
 */
function message_library_help_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-message-library-search-page') {
    $path = drupal_get_path('module', 'message_library_help');
    $form['#attached']['js'][]  = $path . '/message_library_help.js';
  }
}

/**
 * Implements MODULENAME_preprocess_hook()
 */
function message_library_help_preprocess_views_exposed_form(&$vars) {
  $form = $vars['form'];
  if ($form['#id'] == 'views-exposed-form-message-library-search-page') {
    // Add the help boxes
    $box_names = array(
      'ml_help_general',
      'ml_help_quick_search',
    );
    foreach ($box_names as $box_name) {
      $box = module_invoke('boxes', 'block_view', $box_name);
      $vars[$box_name] = $box['content'];
    }
  }
}
